import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import { AuthProvider } from "@/components/auth/auth-provider";

const pretendard = localFont({
  src: "../../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

/**
 * Wanted Sans · 토스인베스트의 Toss Product Sans 를 대신할 후보.
 * 그 폰트는 토스 전용 라이선스라 쓸 수 없고, 같은 「한글 프로덕트 산세리프」 계열 중
 * x-height 가 크고 기본 자간이 조여 있어 결이 가장 가깝다 (OFL · 가변 400~1000).
 * `/design/type` 에서 Pretendard 와 나란히 견주는 중 · 정해지면 한쪽을 지운다.
 */
const wantedSans = localFont({
  src: "../../node_modules/wanted-sans/fonts/webfonts/variable/complete/woff2/WantedSansVariable.woff2",
  display: "swap",
  weight: "400 1000",
  variable: "--font-wanted",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      translate="no"
      className={`notranslate ${pretendard.variable} ${wantedSans.variable}`}
      suppressHydrationWarning
    >
      <head>
        <meta name="google" content="notranslate" />
      </head>
      <body className="antialiased bg-canvas text-content">
        <Providers>
          <AuthProvider>{children}</AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
