ALTER TABLE company_info ADD COLUMN IF NOT EXISTS representative VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE company_info ADD COLUMN IF NOT EXISTS ecommerce_number VARCHAR(100) NOT NULL DEFAULT '';
